FROM alpine:latest

ADD run_v2ray.sh /usr/local/bin/run_v2ray.sh
ADD v2ray_unzip/v2ray /usr/local/bin/v2ray
RUN chmod +x /usr/local/bin/run_v2ray.sh
RUN chmod +x /usr/local/bin/v2ray

RUN apk add --no-cache ca-certificates

RUN install -d /usr/local/etc/v2ray
ADD config.json.server /usr/local/etc/v2ray/config.json

ENTRYPOINT ["/usr/local/bin/run_v2ray.sh"]
