FROM alpine:3.5

ADD v2ray_unzip/v2ray /usr/local/bin/v2ray
RUN chmod +x /usr/local/bin/v2ray

RUN apk add --no-cache ca-certificates

# V2Ray new configuration
RUN install -d /usr/local/etc/v2ray
ADD config.json.server /usr/local/etc/v2ray/config.json

# Run V2Ray
ENTRYPOINT ["/usr/local/bin/v2ray", "-config", "/usr/local/etc/v2ray/config.json"]
